name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: build with cmake
      continue-on-error: true
      run: |
        cmake -B build
        cmake --build build

  if: ${{ success() }}
    push:
      runs-on: ubuntu-latest
      steps:
      - uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_GITHUB }}
          src_path: /.
          src_branch: main
          dst_branch: master
          dst_path: /.
          dst_owner: EpitechPromo2025
          dst_repo_name: B-YEP-400-TLS-4-1-indiestudio-ilan.chekroun
          commit_message: "[CA] - Push to ID: ${{ github.run_id }} by github action from ${{ github.repository }}"  